export const COLUMS_DEFAULT = [
  { header: "Number", accessorKey: "consecutive" },
  { header: "Date", accessorKey: "date" },
  { header: "Customer", accessorKey: "customer" },
  { header: "PO", accessorKey: "PO" },
  { header: "SKU", accessorKey: "sku" },
  { header: "State", accessorKey: "state" },
  { header: "QTY", accessorKey: "totalProds" },
  { header: "Walmart Selling Price", accessorKey: "priceForProd" },
  {
    header: "Total Selling Price",
    accessorKey: "totalCharge",
  },
  { header: "COGS", accessorKey: "cogs" },
  { header: "Walmart Fees", accessorKey: "walFees" },
  { header: "Net Proceeds", accessorKey: "netProceeds" },
  { header: "Net Profit", accessorKey: "netProfit" },
  { header: "Walmart Category Fee", accessorKey: "walFeesPer" },
  { header: "ROI", accessorKey: "ROI" },
];
